"""Versioned warehouse lineage and candidate-isolation contracts."""

from reviewlens.warehouse.candidates import (
    CandidateDefinition,
    CandidateLayer,
    CandidateLease,
    CandidateState,
    InMemoryCandidateRegistry,
    PhysicalRelationRef,
    ProcessingInput,
    ProcessingInputKind,
    ProcessingRunDefinition,
    WarehouseCandidateError,
    build_candidate_definition,
    build_processing_run,
)
from reviewlens.warehouse.quality import (
    DQ_CONTRACT_VERSION,
    DQFinding,
    DQGateResult,
    DQGateStatus,
    DQSeverity,
    WarehouseQualityError,
    evaluate_quality_gate,
)
from reviewlens.warehouse.revisions import (
    REVISION_POLICY_VERSION,
    UNKNOWN_MEMBER_POLICY_VERSION,
    DimensionEntity,
    DimensionRevision,
    RevisionDisposition,
    RevisionResolution,
    UnknownMember,
    WarehouseRevisionError,
    resolve_dimension_revisions,
    unknown_member,
)

__all__ = [
    "DQ_CONTRACT_VERSION",
    "REVISION_POLICY_VERSION",
    "UNKNOWN_MEMBER_POLICY_VERSION",
    "CandidateDefinition",
    "CandidateLayer",
    "CandidateLease",
    "CandidateState",
    "DQFinding",
    "DQGateResult",
    "DQGateStatus",
    "DQSeverity",
    "DimensionEntity",
    "DimensionRevision",
    "InMemoryCandidateRegistry",
    "PhysicalRelationRef",
    "ProcessingInput",
    "ProcessingInputKind",
    "ProcessingRunDefinition",
    "RevisionDisposition",
    "RevisionResolution",
    "UnknownMember",
    "WarehouseCandidateError",
    "WarehouseQualityError",
    "WarehouseRevisionError",
    "build_candidate_definition",
    "build_processing_run",
    "evaluate_quality_gate",
    "resolve_dimension_revisions",
    "unknown_member",
]
