-- ReviewLens M1 Snowflake foundation.
-- This file is intentionally secret-free and safe to commit.
-- Run with an account bootstrap role; application roles are created in IMP-M1-007.

USE ROLE ACCOUNTADMIN;

CREATE RESOURCE MONITOR IF NOT EXISTS REVIEWLENS_MONTHLY_MONITOR
  WITH
    CREDIT_QUOTA = 10
    FREQUENCY = MONTHLY
    START_TIMESTAMP = IMMEDIATELY
    TRIGGERS
      ON 50 PERCENT DO NOTIFY
      ON 80 PERCENT DO NOTIFY
      ON 100 PERCENT DO SUSPEND_IMMEDIATE;

-- Reconcile quota and triggers without resetting the monthly schedule on every run.
ALTER RESOURCE MONITOR REVIEWLENS_MONTHLY_MONITOR SET
  CREDIT_QUOTA = 10
  TRIGGERS
    ON 50 PERCENT DO NOTIFY
    ON 80 PERCENT DO NOTIFY
    ON 100 PERCENT DO SUSPEND_IMMEDIATE;

CREATE WAREHOUSE IF NOT EXISTS REVIEWLENS_WH
  WITH
    WAREHOUSE_SIZE = XSMALL
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    RESOURCE_MONITOR = REVIEWLENS_MONTHLY_MONITOR
    COMMENT = 'ReviewLens local portfolio warehouse; approved private data only';

ALTER WAREHOUSE REVIEWLENS_WH SET
  WAREHOUSE_SIZE = XSMALL
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  RESOURCE_MONITOR = REVIEWLENS_MONTHLY_MONITOR;

CREATE DATABASE IF NOT EXISTS REVIEWLENS
  COMMENT = 'ReviewLens local portfolio database; approved private data only';

CREATE SCHEMA IF NOT EXISTS REVIEWLENS.BRONZE;
CREATE SCHEMA IF NOT EXISTS REVIEWLENS.SILVER;
CREATE SCHEMA IF NOT EXISTS REVIEWLENS.AI;
CREATE SCHEMA IF NOT EXISTS REVIEWLENS.GOLD;
CREATE SCHEMA IF NOT EXISTS REVIEWLENS.AUDIT;
CREATE SCHEMA IF NOT EXISTS REVIEWLENS.QUARANTINE;

CREATE FILE FORMAT IF NOT EXISTS REVIEWLENS.BRONZE.JSONL_FORMAT
  TYPE = JSON
  STRIP_OUTER_ARRAY = FALSE
  COMMENT = 'JSONL/JSON format used by ReviewLens synthetic stage smoke tests';

CREATE FILE FORMAT IF NOT EXISTS REVIEWLENS.BRONZE.OLIST_CSV_FORMAT
  TYPE = CSV
  SKIP_HEADER = 1
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  EMPTY_FIELD_AS_NULL = TRUE
  NULL_IF = ('', 'NA')
  ENCODING = 'UTF8'
  COMMENT = 'CSV contract for the nine Olist Brazilian e-commerce source files';
