-- ReviewLens M1 least-privilege account roles.
-- This owner-operated bootstrap is secret-free and safe to re-run.
-- Runtime/service credentials are assigned to these roles in IMP-M1-008.

USE ROLE ACCOUNTADMIN;

CREATE ROLE IF NOT EXISTS REVIEWLENS_OWNER
  COMMENT = 'Top custom ReviewLens role; parent of service roles, never an app identity';
CREATE ROLE IF NOT EXISTS INGEST_ROLE
  COMMENT = 'Loads approved objects into Bronze and Quarantine';
CREATE ROLE IF NOT EXISTS TRANSFORMER_ROLE
  COMMENT = 'Reads Bronze and builds Silver through dbt';
CREATE ROLE IF NOT EXISTS AI_ENRICH_ROLE
  COMMENT = 'Reads approved review projections and writes scoped AI outputs';
CREATE ROLE IF NOT EXISTS VECTOR_INDEXER_ROLE
  COMMENT = 'Reads approved RAG documents for the separate Chroma writer';
CREATE ROLE IF NOT EXISTS GOLD_BUILDER_ROLE
  COMMENT = 'Builds versioned Gold objects from approved Silver and AI inputs';
CREATE ROLE IF NOT EXISTS ANALYST_ROLE
  COMMENT = 'Reads explicitly approved Gold views';
CREATE ROLE IF NOT EXISTS TEXT_TO_SQL_ROLE
  COMMENT = 'Read-only access to explicitly approved Gold semantic views';
CREATE ROLE IF NOT EXISTS RAG_ROLE
  COMMENT = 'Reads explicitly approved release-bound RAG document views';

-- Keep every custom role in the SYSADMIN hierarchy without granting system roles downward.
GRANT ROLE INGEST_ROLE TO ROLE REVIEWLENS_OWNER;
GRANT ROLE TRANSFORMER_ROLE TO ROLE REVIEWLENS_OWNER;
GRANT ROLE AI_ENRICH_ROLE TO ROLE REVIEWLENS_OWNER;
GRANT ROLE VECTOR_INDEXER_ROLE TO ROLE REVIEWLENS_OWNER;
GRANT ROLE GOLD_BUILDER_ROLE TO ROLE REVIEWLENS_OWNER;
GRANT ROLE ANALYST_ROLE TO ROLE REVIEWLENS_OWNER;
GRANT ROLE TEXT_TO_SQL_ROLE TO ROLE REVIEWLENS_OWNER;
GRANT ROLE RAG_ROLE TO ROLE REVIEWLENS_OWNER;
GRANT ROLE REVIEWLENS_OWNER TO ROLE SYSADMIN;

-- Text-to-SQL has an isolated, tightly bounded warehouse.
CREATE WAREHOUSE IF NOT EXISTS REVIEWLENS_SQL_WH
  WITH
    WAREHOUSE_SIZE = XSMALL
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    RESOURCE_MONITOR = REVIEWLENS_MONTHLY_MONITOR
    COMMENT = 'ReviewLens read-only Text-to-SQL warehouse; approved private data only';

ALTER WAREHOUSE REVIEWLENS_SQL_WH SET
  WAREHOUSE_SIZE = XSMALL
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  RESOURCE_MONITOR = REVIEWLENS_MONTHLY_MONITOR;

-- INGEST_ROLE: write-only lake-to-Bronze/Quarantine boundary.
GRANT USAGE ON WAREHOUSE REVIEWLENS_WH TO ROLE INGEST_ROLE;
GRANT USAGE ON DATABASE REVIEWLENS TO ROLE INGEST_ROLE;
GRANT USAGE ON SCHEMA REVIEWLENS.BRONZE TO ROLE INGEST_ROLE;
GRANT USAGE ON SCHEMA REVIEWLENS.QUARANTINE TO ROLE INGEST_ROLE;
GRANT USAGE ON STAGE REVIEWLENS.BRONZE.R2_STAGE TO ROLE INGEST_ROLE;
GRANT USAGE ON FILE FORMAT REVIEWLENS.BRONZE.JSONL_FORMAT TO ROLE INGEST_ROLE;
GRANT USAGE ON FILE FORMAT REVIEWLENS.BRONZE.OLIST_CSV_FORMAT TO ROLE INGEST_ROLE;
GRANT INSERT ON ALL TABLES IN SCHEMA REVIEWLENS.BRONZE TO ROLE INGEST_ROLE;
GRANT INSERT ON FUTURE TABLES IN SCHEMA REVIEWLENS.BRONZE TO ROLE INGEST_ROLE;
GRANT INSERT ON ALL TABLES IN SCHEMA REVIEWLENS.QUARANTINE TO ROLE INGEST_ROLE;
GRANT INSERT ON FUTURE TABLES IN SCHEMA REVIEWLENS.QUARANTINE TO ROLE INGEST_ROLE;

-- TRANSFORMER_ROLE: broad only inside its declared Bronze-read/Silver-build layers.
GRANT USAGE ON WAREHOUSE REVIEWLENS_WH TO ROLE TRANSFORMER_ROLE;
GRANT USAGE ON DATABASE REVIEWLENS TO ROLE TRANSFORMER_ROLE;
GRANT USAGE ON SCHEMA REVIEWLENS.BRONZE TO ROLE TRANSFORMER_ROLE;
GRANT USAGE ON SCHEMA REVIEWLENS.SILVER TO ROLE TRANSFORMER_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA REVIEWLENS.BRONZE TO ROLE TRANSFORMER_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA REVIEWLENS.BRONZE TO ROLE TRANSFORMER_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA REVIEWLENS.BRONZE TO ROLE TRANSFORMER_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA REVIEWLENS.BRONZE TO ROLE TRANSFORMER_ROLE;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA REVIEWLENS.SILVER TO ROLE TRANSFORMER_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA REVIEWLENS.SILVER TO ROLE TRANSFORMER_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON FUTURE TABLES IN SCHEMA REVIEWLENS.SILVER TO ROLE TRANSFORMER_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA REVIEWLENS.SILVER TO ROLE TRANSFORMER_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA REVIEWLENS.SILVER TO ROLE TRANSFORMER_ROLE;

-- AI roles get container/compute access here. Object grants stay explicit in AI migrations.
GRANT USAGE ON WAREHOUSE REVIEWLENS_WH TO ROLE AI_ENRICH_ROLE;
GRANT USAGE ON DATABASE REVIEWLENS TO ROLE AI_ENRICH_ROLE;
GRANT USAGE ON SCHEMA REVIEWLENS.SILVER TO ROLE AI_ENRICH_ROLE;
GRANT USAGE ON SCHEMA REVIEWLENS.AI TO ROLE AI_ENRICH_ROLE;
GRANT USAGE ON SCHEMA REVIEWLENS.AUDIT TO ROLE AI_ENRICH_ROLE;

GRANT USAGE ON WAREHOUSE REVIEWLENS_WH TO ROLE VECTOR_INDEXER_ROLE;
GRANT USAGE ON DATABASE REVIEWLENS TO ROLE VECTOR_INDEXER_ROLE;
GRANT USAGE ON SCHEMA REVIEWLENS.AI TO ROLE VECTOR_INDEXER_ROLE;

-- Gold builder owns only objects it creates; source grants remain object-specific.
GRANT USAGE ON WAREHOUSE REVIEWLENS_WH TO ROLE GOLD_BUILDER_ROLE;
GRANT USAGE ON DATABASE REVIEWLENS TO ROLE GOLD_BUILDER_ROLE;
GRANT USAGE ON SCHEMA REVIEWLENS.SILVER TO ROLE GOLD_BUILDER_ROLE;
GRANT USAGE ON SCHEMA REVIEWLENS.AI TO ROLE GOLD_BUILDER_ROLE;
GRANT USAGE ON SCHEMA REVIEWLENS.GOLD TO ROLE GOLD_BUILDER_ROLE;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA REVIEWLENS.GOLD TO ROLE GOLD_BUILDER_ROLE;

-- Consumption roles get containers only; approved views are granted by release migrations.
GRANT USAGE ON WAREHOUSE REVIEWLENS_WH TO ROLE ANALYST_ROLE;
GRANT USAGE ON DATABASE REVIEWLENS TO ROLE ANALYST_ROLE;
GRANT USAGE ON SCHEMA REVIEWLENS.GOLD TO ROLE ANALYST_ROLE;

GRANT USAGE ON WAREHOUSE REVIEWLENS_SQL_WH TO ROLE TEXT_TO_SQL_ROLE;
GRANT USAGE ON DATABASE REVIEWLENS TO ROLE TEXT_TO_SQL_ROLE;
GRANT USAGE ON SCHEMA REVIEWLENS.GOLD TO ROLE TEXT_TO_SQL_ROLE;

GRANT USAGE ON WAREHOUSE REVIEWLENS_WH TO ROLE RAG_ROLE;
GRANT USAGE ON DATABASE REVIEWLENS TO ROLE RAG_ROLE;
GRANT USAGE ON SCHEMA REVIEWLENS.AI TO ROLE RAG_ROLE;
