-- ReviewLens M1 dedicated Snowflake service identities.
-- Secret-free and safe to re-run: new users start disabled, existing users are not re-disabled.
-- Public keys are registered out-of-band with the named-key workflow in the runbook.

USE ROLE ACCOUNTADMIN;

CREATE USER IF NOT EXISTS REVIEWLENS_INGEST_SVC
  TYPE = SERVICE
  DEFAULT_ROLE = INGEST_ROLE
  DEFAULT_WAREHOUSE = REVIEWLENS_WH
  DEFAULT_SECONDARY_ROLES = ()
  DISABLED = TRUE
  COMMENT = 'ReviewLens ingestion service; enable only after a role-restricted key is registered';
ALTER USER IF EXISTS REVIEWLENS_INGEST_SVC SET
  TYPE = SERVICE DEFAULT_ROLE = INGEST_ROLE DEFAULT_WAREHOUSE = REVIEWLENS_WH
  DEFAULT_SECONDARY_ROLES = ();
GRANT ROLE INGEST_ROLE TO USER REVIEWLENS_INGEST_SVC;

CREATE USER IF NOT EXISTS REVIEWLENS_TRANSFORM_SVC
  TYPE = SERVICE
  DEFAULT_ROLE = TRANSFORMER_ROLE
  DEFAULT_WAREHOUSE = REVIEWLENS_WH
  DEFAULT_SECONDARY_ROLES = ()
  DISABLED = TRUE
  COMMENT = 'ReviewLens dbt transformation service; enable only after a role-restricted key is registered';
ALTER USER IF EXISTS REVIEWLENS_TRANSFORM_SVC SET
  TYPE = SERVICE DEFAULT_ROLE = TRANSFORMER_ROLE DEFAULT_WAREHOUSE = REVIEWLENS_WH
  DEFAULT_SECONDARY_ROLES = ();
GRANT ROLE TRANSFORMER_ROLE TO USER REVIEWLENS_TRANSFORM_SVC;

CREATE USER IF NOT EXISTS REVIEWLENS_AI_ENRICH_SVC
  TYPE = SERVICE
  DEFAULT_ROLE = AI_ENRICH_ROLE
  DEFAULT_WAREHOUSE = REVIEWLENS_WH
  DEFAULT_SECONDARY_ROLES = ()
  DISABLED = TRUE
  COMMENT = 'ReviewLens AI enrichment service; enable only after a role-restricted key is registered';
ALTER USER IF EXISTS REVIEWLENS_AI_ENRICH_SVC SET
  TYPE = SERVICE DEFAULT_ROLE = AI_ENRICH_ROLE DEFAULT_WAREHOUSE = REVIEWLENS_WH
  DEFAULT_SECONDARY_ROLES = ();
GRANT ROLE AI_ENRICH_ROLE TO USER REVIEWLENS_AI_ENRICH_SVC;

CREATE USER IF NOT EXISTS REVIEWLENS_VECTOR_INDEXER_SVC
  TYPE = SERVICE
  DEFAULT_ROLE = VECTOR_INDEXER_ROLE
  DEFAULT_WAREHOUSE = REVIEWLENS_WH
  DEFAULT_SECONDARY_ROLES = ()
  DISABLED = TRUE
  COMMENT = 'ReviewLens Chroma index writer; enable only after a role-restricted key is registered';
ALTER USER IF EXISTS REVIEWLENS_VECTOR_INDEXER_SVC SET
  TYPE = SERVICE DEFAULT_ROLE = VECTOR_INDEXER_ROLE DEFAULT_WAREHOUSE = REVIEWLENS_WH
  DEFAULT_SECONDARY_ROLES = ();
GRANT ROLE VECTOR_INDEXER_ROLE TO USER REVIEWLENS_VECTOR_INDEXER_SVC;

CREATE USER IF NOT EXISTS REVIEWLENS_GOLD_BUILDER_SVC
  TYPE = SERVICE
  DEFAULT_ROLE = GOLD_BUILDER_ROLE
  DEFAULT_WAREHOUSE = REVIEWLENS_WH
  DEFAULT_SECONDARY_ROLES = ()
  DISABLED = TRUE
  COMMENT = 'ReviewLens Gold build service; enable only after a role-restricted key is registered';
ALTER USER IF EXISTS REVIEWLENS_GOLD_BUILDER_SVC SET
  TYPE = SERVICE DEFAULT_ROLE = GOLD_BUILDER_ROLE DEFAULT_WAREHOUSE = REVIEWLENS_WH
  DEFAULT_SECONDARY_ROLES = ();
GRANT ROLE GOLD_BUILDER_ROLE TO USER REVIEWLENS_GOLD_BUILDER_SVC;

CREATE USER IF NOT EXISTS REVIEWLENS_ANALYTICS_SVC
  TYPE = SERVICE
  DEFAULT_ROLE = ANALYST_ROLE
  DEFAULT_WAREHOUSE = REVIEWLENS_WH
  DEFAULT_SECONDARY_ROLES = ()
  DISABLED = TRUE
  COMMENT = 'ReviewLens dashboard analytics reader; enable only after a role-restricted key is registered';
ALTER USER IF EXISTS REVIEWLENS_ANALYTICS_SVC SET
  TYPE = SERVICE DEFAULT_ROLE = ANALYST_ROLE DEFAULT_WAREHOUSE = REVIEWLENS_WH
  DEFAULT_SECONDARY_ROLES = ();
GRANT ROLE ANALYST_ROLE TO USER REVIEWLENS_ANALYTICS_SVC;

CREATE USER IF NOT EXISTS REVIEWLENS_TEXT_TO_SQL_SVC
  TYPE = SERVICE
  DEFAULT_ROLE = TEXT_TO_SQL_ROLE
  DEFAULT_WAREHOUSE = REVIEWLENS_SQL_WH
  DEFAULT_SECONDARY_ROLES = ()
  DISABLED = TRUE
  COMMENT = 'ReviewLens guarded Text-to-SQL executor; enable only after a role-restricted key is registered';
ALTER USER IF EXISTS REVIEWLENS_TEXT_TO_SQL_SVC SET
  TYPE = SERVICE DEFAULT_ROLE = TEXT_TO_SQL_ROLE DEFAULT_WAREHOUSE = REVIEWLENS_SQL_WH
  DEFAULT_SECONDARY_ROLES = ();
GRANT ROLE TEXT_TO_SQL_ROLE TO USER REVIEWLENS_TEXT_TO_SQL_SVC;

CREATE USER IF NOT EXISTS REVIEWLENS_RAG_SVC
  TYPE = SERVICE
  DEFAULT_ROLE = RAG_ROLE
  DEFAULT_WAREHOUSE = REVIEWLENS_WH
  DEFAULT_SECONDARY_ROLES = ()
  DISABLED = TRUE
  COMMENT = 'ReviewLens authoritative RAG evidence reader; enable only after a role-restricted key is registered';
ALTER USER IF EXISTS REVIEWLENS_RAG_SVC SET
  TYPE = SERVICE DEFAULT_ROLE = RAG_ROLE DEFAULT_WAREHOUSE = REVIEWLENS_WH
  DEFAULT_SECONDARY_ROLES = ();
GRANT ROLE RAG_ROLE TO USER REVIEWLENS_RAG_SVC;
