-- ReviewLens M1 append-only audit ledger foundation.
-- Secret-free and safe to re-run. Standard-table primary keys are informational;
-- producers remain responsible for deterministic IDs and idempotent writes.

USE ROLE ACCOUNTADMIN;
USE DATABASE REVIEWLENS;

CREATE SCHEMA IF NOT EXISTS REVIEWLENS.AUDIT;

CREATE TABLE IF NOT EXISTS REVIEWLENS.AUDIT.INGESTION_EVENT (
  EVENT_ID VARCHAR(64) NOT NULL,
  LEDGER_SCHEMA_VERSION NUMBER(10, 0) NOT NULL DEFAULT 1,
  SOURCE_RELEASE_ID VARCHAR(64) NOT NULL,
  INGESTION_BATCH_ID VARCHAR(64) NOT NULL,
  DATASET_RUN_ID VARCHAR(64) NOT NULL,
  ATTEMPT_ID VARCHAR(64) NOT NULL,
  STATE VARCHAR(32) NOT NULL,
  EVENT_AT TIMESTAMP_TZ(9) NOT NULL,
  TRACE_ID VARCHAR(128) NOT NULL,
  RECORD_COUNT NUMBER(38, 0),
  SANITIZED_METADATA VARIANT,
  RECORDED_AT TIMESTAMP_TZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT PK_AUDIT_INGESTION_EVENT PRIMARY KEY (EVENT_ID)
)
COMMENT = 'Append-only ingestion state events with identifiers, counts and sanitized metadata';

CREATE TABLE IF NOT EXISTS REVIEWLENS.AUDIT.SOURCE_FILE_EVENT (
  EVENT_ID VARCHAR(64) NOT NULL,
  LEDGER_SCHEMA_VERSION NUMBER(10, 0) NOT NULL DEFAULT 1,
  SOURCE_RELEASE_ID VARCHAR(64) NOT NULL,
  INGESTION_BATCH_ID VARCHAR(64) NOT NULL,
  DATASET_RUN_ID VARCHAR(64) NOT NULL,
  SOURCE_FILE_NAME VARCHAR(256) NOT NULL,
  SOURCE_OBJECT_URI VARCHAR(2048),
  SOURCE_OBJECT_SHA256 VARCHAR(64) NOT NULL,
  SOURCE_SIZE_BYTES NUMBER(38, 0) NOT NULL,
  PHYSICAL_ROW_COUNT NUMBER(38, 0),
  ACCEPTED_ROW_COUNT NUMBER(38, 0),
  REJECTED_ROW_COUNT NUMBER(38, 0),
  STATUS VARCHAR(32) NOT NULL,
  EVENT_AT TIMESTAMP_TZ(9) NOT NULL,
  TRACE_ID VARCHAR(128) NOT NULL,
  SANITIZED_METADATA VARIANT,
  RECORDED_AT TIMESTAMP_TZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT PK_AUDIT_SOURCE_FILE_EVENT PRIMARY KEY (EVENT_ID)
)
COMMENT = 'Append-only source-file checksum, location and reconciliation events';

CREATE TABLE IF NOT EXISTS REVIEWLENS.AUDIT.PROCESS_EVENT (
  EVENT_ID VARCHAR(64) NOT NULL,
  LEDGER_SCHEMA_VERSION NUMBER(10, 0) NOT NULL DEFAULT 1,
  DATASET_RUN_ID VARCHAR(64) NOT NULL,
  PROCESS_RUN_ID VARCHAR(64) NOT NULL,
  ATTEMPT_ID VARCHAR(64) NOT NULL,
  PHASE VARCHAR(32) NOT NULL,
  STATE VARCHAR(32) NOT NULL,
  INPUT_RELEASE_ID VARCHAR(64),
  CANDIDATE_VERSION VARCHAR(128),
  ROW_COUNT NUMBER(38, 0),
  ERROR_CODE VARCHAR(128),
  EVENT_AT TIMESTAMP_TZ(9) NOT NULL,
  TRACE_ID VARCHAR(128) NOT NULL,
  SANITIZED_METADATA VARIANT,
  RECORDED_AT TIMESTAMP_TZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT PK_AUDIT_PROCESS_EVENT PRIMARY KEY (EVENT_ID)
)
COMMENT = 'Append-only Silver, AI, Gold and index process state events';

CREATE TABLE IF NOT EXISTS REVIEWLENS.AUDIT.RELEASE_EVENT (
  EVENT_ID VARCHAR(64) NOT NULL,
  LEDGER_SCHEMA_VERSION NUMBER(10, 0) NOT NULL DEFAULT 1,
  RELEASE_ID VARCHAR(64) NOT NULL,
  DATASET_RUN_ID VARCHAR(64) NOT NULL,
  EVENT_TYPE VARCHAR(32) NOT NULL,
  PREVIOUS_RELEASE_ID VARCHAR(64),
  SILVER_VERSION VARCHAR(128) NOT NULL,
  AI_VERSION VARCHAR(128),
  GOLD_VERSION VARCHAR(128) NOT NULL,
  INDEX_VERSION VARCHAR(128),
  ACTOR_SERVICE VARCHAR(128) NOT NULL,
  REASON_CODE VARCHAR(128),
  EVENT_AT TIMESTAMP_TZ(9) NOT NULL,
  TRACE_ID VARCHAR(128) NOT NULL,
  SANITIZED_METADATA VARIANT,
  RECORDED_AT TIMESTAMP_TZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT PK_AUDIT_RELEASE_EVENT PRIMARY KEY (EVENT_ID)
)
COMMENT = 'Append-only created, activated, rolled-back, invalidated and revoked release events';

CREATE TABLE IF NOT EXISTS REVIEWLENS.AUDIT.ACTIVE_RELEASE_POINTER (
  POINTER_NAME VARCHAR(64) NOT NULL,
  LEDGER_SCHEMA_VERSION NUMBER(10, 0) NOT NULL DEFAULT 1,
  RELEASE_ID VARCHAR(64) NOT NULL,
  ACTIVATION_EVENT_ID VARCHAR(64) NOT NULL,
  POINTER_VERSION NUMBER(38, 0) NOT NULL,
  ACTIVATED_AT TIMESTAMP_TZ(9) NOT NULL,
  UPDATED_AT TIMESTAMP_TZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT PK_AUDIT_ACTIVE_RELEASE_POINTER PRIMARY KEY (POINTER_NAME)
)
COMMENT = 'Guarded local active-release pointer; mutation is reserved for a later owner-executed release procedure';

CREATE TABLE IF NOT EXISTS REVIEWLENS.AUDIT.AI_INVOCATION_EVENT (
  INVOCATION_ID VARCHAR(64) NOT NULL,
  LEDGER_SCHEMA_VERSION NUMBER(10, 0) NOT NULL DEFAULT 1,
  DATASET_RUN_ID VARCHAR(64) NOT NULL,
  PROCESS_RUN_ID VARCHAR(64) NOT NULL,
  SOURCE_RECORD_HASH VARCHAR(64) NOT NULL,
  TASK_TYPE VARCHAR(32) NOT NULL,
  PROVIDER_NAME VARCHAR(64) NOT NULL,
  MODEL_ID VARCHAR(256) NOT NULL,
  PROMPT_VERSION VARCHAR(128) NOT NULL,
  OUTPUT_SCHEMA_VERSION VARCHAR(128) NOT NULL,
  TAXONOMY_VERSION VARCHAR(128),
  PROVIDER_POLICY_VERSION VARCHAR(128) NOT NULL,
  ATTEMPT_NUMBER NUMBER(10, 0) NOT NULL,
  STATUS VARCHAR(32) NOT NULL,
  INPUT_TOKEN_COUNT NUMBER(38, 0) NOT NULL DEFAULT 0,
  OUTPUT_TOKEN_COUNT NUMBER(38, 0) NOT NULL DEFAULT 0,
  COST_USD NUMBER(18, 8) NOT NULL DEFAULT 0,
  LATENCY_MS NUMBER(38, 0),
  REQUEST_HASH VARCHAR(64) NOT NULL,
  RESPONSE_HASH VARCHAR(64),
  SANITIZED_ERROR_CODE VARCHAR(128),
  TRACE_ID VARCHAR(128) NOT NULL,
  STARTED_AT TIMESTAMP_TZ(9) NOT NULL,
  COMPLETED_AT TIMESTAMP_TZ(9),
  RECORDED_AT TIMESTAMP_TZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT PK_AUDIT_AI_INVOCATION_EVENT PRIMARY KEY (INVOCATION_ID)
)
COMMENT = 'Immutable AI attempt ledger with hashes, versions, tokens, cost, latency and sanitized error code';

CREATE VIEW IF NOT EXISTS REVIEWLENS.AUDIT.SCHEMA_COMPATIBILITY
COMMENT = 'Constant audit contract marker; querying it requires compute but creating it does not resume a warehouse'
AS
SELECT
  'IMP-M1-013-AUDIT-V1'::VARCHAR(128) AS MIGRATION_ID,
  1::NUMBER(10, 0) AS SCHEMA_VERSION,
  'infra/snowflake/004_audit_ledgers.sql'::VARCHAR(256) AS ARTIFACT_NAME;

-- Runtime roles receive exact append/read grants only. No event ledger grants
-- UPDATE, DELETE, TRUNCATE, OWNERSHIP or schema-wide future object privileges.
GRANT USAGE ON SCHEMA REVIEWLENS.AUDIT TO ROLE INGEST_ROLE;
GRANT SELECT, INSERT ON TABLE REVIEWLENS.AUDIT.INGESTION_EVENT TO ROLE INGEST_ROLE;
GRANT SELECT, INSERT ON TABLE REVIEWLENS.AUDIT.SOURCE_FILE_EVENT TO ROLE INGEST_ROLE;

GRANT USAGE ON SCHEMA REVIEWLENS.AUDIT TO ROLE TRANSFORMER_ROLE;
GRANT SELECT, INSERT ON TABLE REVIEWLENS.AUDIT.PROCESS_EVENT TO ROLE TRANSFORMER_ROLE;

GRANT USAGE ON SCHEMA REVIEWLENS.AUDIT TO ROLE AI_ENRICH_ROLE;
GRANT SELECT, INSERT ON TABLE REVIEWLENS.AUDIT.PROCESS_EVENT TO ROLE AI_ENRICH_ROLE;
GRANT SELECT, INSERT ON TABLE REVIEWLENS.AUDIT.AI_INVOCATION_EVENT TO ROLE AI_ENRICH_ROLE;

GRANT USAGE ON SCHEMA REVIEWLENS.AUDIT TO ROLE VECTOR_INDEXER_ROLE;
GRANT SELECT, INSERT ON TABLE REVIEWLENS.AUDIT.PROCESS_EVENT TO ROLE VECTOR_INDEXER_ROLE;

GRANT USAGE ON SCHEMA REVIEWLENS.AUDIT TO ROLE GOLD_BUILDER_ROLE;
GRANT SELECT, INSERT ON TABLE REVIEWLENS.AUDIT.PROCESS_EVENT TO ROLE GOLD_BUILDER_ROLE;
GRANT SELECT ON TABLE REVIEWLENS.AUDIT.RELEASE_EVENT TO ROLE GOLD_BUILDER_ROLE;
GRANT SELECT ON TABLE REVIEWLENS.AUDIT.ACTIVE_RELEASE_POINTER TO ROLE GOLD_BUILDER_ROLE;

GRANT USAGE ON SCHEMA REVIEWLENS.AUDIT TO ROLE ANALYST_ROLE;
GRANT SELECT ON TABLE REVIEWLENS.AUDIT.ACTIVE_RELEASE_POINTER TO ROLE ANALYST_ROLE;

GRANT USAGE ON SCHEMA REVIEWLENS.AUDIT TO ROLE TEXT_TO_SQL_ROLE;
GRANT SELECT ON TABLE REVIEWLENS.AUDIT.ACTIVE_RELEASE_POINTER TO ROLE TEXT_TO_SQL_ROLE;

GRANT USAGE ON SCHEMA REVIEWLENS.AUDIT TO ROLE RAG_ROLE;
GRANT SELECT ON TABLE REVIEWLENS.AUDIT.ACTIVE_RELEASE_POINTER TO ROLE RAG_ROLE;
