-- ReviewLens M2 immutable Olist Bronze tables and load ledger.
-- Secret-free, safe to re-run, and intentionally contains no row-level data.

USE ROLE ACCOUNTADMIN;
USE DATABASE REVIEWLENS;

CREATE FILE FORMAT IF NOT EXISTS REVIEWLENS.BRONZE.OLIST_PARQUET_FORMAT
  TYPE = PARQUET
  COMPRESSION = AUTO
  BINARY_AS_TEXT = FALSE
  USE_LOGICAL_TYPE = TRUE
  USE_VECTORIZED_SCANNER = TRUE
  COMMENT = 'Typed Olist raw Parquet produced by ReviewLens ingestion';

CREATE TABLE IF NOT EXISTS REVIEWLENS.BRONZE.BRZ_OLIST_CUSTOMERS_RAW (
  CUSTOMER_ID VARCHAR NOT NULL,
  CUSTOMER_UNIQUE_ID VARCHAR NOT NULL,
  CUSTOMER_ZIP_CODE_PREFIX VARCHAR NOT NULL,
  CUSTOMER_CITY VARCHAR NOT NULL,
  CUSTOMER_STATE VARCHAR NOT NULL,
  SOURCE_RELEASE_ID VARCHAR NOT NULL,
  INGESTION_BATCH_ID VARCHAR NOT NULL,
  DATASET_RUN_ID VARCHAR NOT NULL,
  SOURCE_FILE_NAME VARCHAR NOT NULL,
  SOURCE_ROW_NUMBER NUMBER(38, 0) NOT NULL,
  SOURCE_OBJECT_SHA256 VARCHAR(64) NOT NULL,
  RECORD_HASH VARCHAR(64) NOT NULL,
  INGESTED_AT TIMESTAMP_TZ(6) NOT NULL,
  SCHEMA_VERSION VARCHAR NOT NULL,
  RAW_PAYLOAD VARCHAR NOT NULL,
  CONSTRAINT UQ_BRZ_CUSTOMERS_ROW UNIQUE
    (INGESTION_BATCH_ID, DATASET_RUN_ID, RECORD_HASH, SOURCE_ROW_NUMBER)
)
COMMENT = 'Immutable private Olist customer rows with canonical lineage';

CREATE TABLE IF NOT EXISTS REVIEWLENS.BRONZE.BRZ_OLIST_GEOLOCATION_RAW (
  GEOLOCATION_ZIP_CODE_PREFIX VARCHAR NOT NULL,
  GEOLOCATION_LAT NUMBER(38, 18) NOT NULL,
  GEOLOCATION_LNG NUMBER(38, 18) NOT NULL,
  GEOLOCATION_CITY VARCHAR NOT NULL,
  GEOLOCATION_STATE VARCHAR NOT NULL,
  SOURCE_RELEASE_ID VARCHAR NOT NULL,
  INGESTION_BATCH_ID VARCHAR NOT NULL,
  DATASET_RUN_ID VARCHAR NOT NULL,
  SOURCE_FILE_NAME VARCHAR NOT NULL,
  SOURCE_ROW_NUMBER NUMBER(38, 0) NOT NULL,
  SOURCE_OBJECT_SHA256 VARCHAR(64) NOT NULL,
  RECORD_HASH VARCHAR(64) NOT NULL,
  INGESTED_AT TIMESTAMP_TZ(6) NOT NULL,
  SCHEMA_VERSION VARCHAR NOT NULL,
  RAW_PAYLOAD VARCHAR NOT NULL,
  CONSTRAINT UQ_BRZ_GEOLOCATION_ROW UNIQUE
    (INGESTION_BATCH_ID, DATASET_RUN_ID, RECORD_HASH, SOURCE_ROW_NUMBER)
)
COMMENT = 'Immutable private Olist geolocation occurrences with canonical lineage';

CREATE TABLE IF NOT EXISTS REVIEWLENS.BRONZE.BRZ_OLIST_ORDER_ITEMS_RAW (
  ORDER_ID VARCHAR NOT NULL,
  ORDER_ITEM_ID NUMBER(38, 0) NOT NULL,
  PRODUCT_ID VARCHAR NOT NULL,
  SELLER_ID VARCHAR NOT NULL,
  SHIPPING_LIMIT_DATE TIMESTAMP_NTZ(6) NOT NULL,
  PRICE NUMBER(38, 18) NOT NULL,
  FREIGHT_VALUE NUMBER(38, 18) NOT NULL,
  SOURCE_RELEASE_ID VARCHAR NOT NULL,
  INGESTION_BATCH_ID VARCHAR NOT NULL,
  DATASET_RUN_ID VARCHAR NOT NULL,
  SOURCE_FILE_NAME VARCHAR NOT NULL,
  SOURCE_ROW_NUMBER NUMBER(38, 0) NOT NULL,
  SOURCE_OBJECT_SHA256 VARCHAR(64) NOT NULL,
  RECORD_HASH VARCHAR(64) NOT NULL,
  INGESTED_AT TIMESTAMP_TZ(6) NOT NULL,
  SCHEMA_VERSION VARCHAR NOT NULL,
  RAW_PAYLOAD VARCHAR NOT NULL,
  CONSTRAINT UQ_BRZ_ORDER_ITEMS_ROW UNIQUE
    (INGESTION_BATCH_ID, DATASET_RUN_ID, RECORD_HASH, SOURCE_ROW_NUMBER)
)
COMMENT = 'Immutable private Olist order-item rows with canonical lineage';

CREATE TABLE IF NOT EXISTS REVIEWLENS.BRONZE.BRZ_OLIST_ORDER_PAYMENTS_RAW (
  ORDER_ID VARCHAR NOT NULL,
  PAYMENT_SEQUENTIAL NUMBER(38, 0) NOT NULL,
  PAYMENT_TYPE VARCHAR NOT NULL,
  PAYMENT_INSTALLMENTS NUMBER(38, 0) NOT NULL,
  PAYMENT_VALUE NUMBER(38, 18) NOT NULL,
  SOURCE_RELEASE_ID VARCHAR NOT NULL,
  INGESTION_BATCH_ID VARCHAR NOT NULL,
  DATASET_RUN_ID VARCHAR NOT NULL,
  SOURCE_FILE_NAME VARCHAR NOT NULL,
  SOURCE_ROW_NUMBER NUMBER(38, 0) NOT NULL,
  SOURCE_OBJECT_SHA256 VARCHAR(64) NOT NULL,
  RECORD_HASH VARCHAR(64) NOT NULL,
  INGESTED_AT TIMESTAMP_TZ(6) NOT NULL,
  SCHEMA_VERSION VARCHAR NOT NULL,
  RAW_PAYLOAD VARCHAR NOT NULL,
  CONSTRAINT UQ_BRZ_ORDER_PAYMENTS_ROW UNIQUE
    (INGESTION_BATCH_ID, DATASET_RUN_ID, RECORD_HASH, SOURCE_ROW_NUMBER)
)
COMMENT = 'Immutable private Olist payment rows with canonical lineage';

CREATE TABLE IF NOT EXISTS REVIEWLENS.BRONZE.BRZ_OLIST_ORDER_REVIEWS_RAW (
  REVIEW_ID VARCHAR NOT NULL,
  ORDER_ID VARCHAR NOT NULL,
  REVIEW_SCORE NUMBER(38, 0) NOT NULL,
  REVIEW_COMMENT_TITLE VARCHAR,
  REVIEW_COMMENT_MESSAGE VARCHAR,
  REVIEW_CREATION_DATE TIMESTAMP_NTZ(6) NOT NULL,
  REVIEW_ANSWER_TIMESTAMP TIMESTAMP_NTZ(6) NOT NULL,
  SOURCE_RELEASE_ID VARCHAR NOT NULL,
  INGESTION_BATCH_ID VARCHAR NOT NULL,
  DATASET_RUN_ID VARCHAR NOT NULL,
  SOURCE_FILE_NAME VARCHAR NOT NULL,
  SOURCE_ROW_NUMBER NUMBER(38, 0) NOT NULL,
  SOURCE_OBJECT_SHA256 VARCHAR(64) NOT NULL,
  RECORD_HASH VARCHAR(64) NOT NULL,
  INGESTED_AT TIMESTAMP_TZ(6) NOT NULL,
  SCHEMA_VERSION VARCHAR NOT NULL,
  RAW_PAYLOAD VARCHAR NOT NULL,
  CONSTRAINT UQ_BRZ_ORDER_REVIEWS_ROW UNIQUE
    (INGESTION_BATCH_ID, DATASET_RUN_ID, RECORD_HASH, SOURCE_ROW_NUMBER)
)
COMMENT = 'Immutable restricted Olist review rows with canonical lineage';

CREATE TABLE IF NOT EXISTS REVIEWLENS.BRONZE.BRZ_OLIST_ORDERS_RAW (
  ORDER_ID VARCHAR NOT NULL,
  CUSTOMER_ID VARCHAR NOT NULL,
  ORDER_STATUS VARCHAR NOT NULL,
  ORDER_PURCHASE_TIMESTAMP TIMESTAMP_NTZ(6) NOT NULL,
  ORDER_APPROVED_AT TIMESTAMP_NTZ(6),
  ORDER_DELIVERED_CARRIER_DATE TIMESTAMP_NTZ(6),
  ORDER_DELIVERED_CUSTOMER_DATE TIMESTAMP_NTZ(6),
  ORDER_ESTIMATED_DELIVERY_DATE TIMESTAMP_NTZ(6) NOT NULL,
  SOURCE_RELEASE_ID VARCHAR NOT NULL,
  INGESTION_BATCH_ID VARCHAR NOT NULL,
  DATASET_RUN_ID VARCHAR NOT NULL,
  SOURCE_FILE_NAME VARCHAR NOT NULL,
  SOURCE_ROW_NUMBER NUMBER(38, 0) NOT NULL,
  SOURCE_OBJECT_SHA256 VARCHAR(64) NOT NULL,
  RECORD_HASH VARCHAR(64) NOT NULL,
  INGESTED_AT TIMESTAMP_TZ(6) NOT NULL,
  SCHEMA_VERSION VARCHAR NOT NULL,
  RAW_PAYLOAD VARCHAR NOT NULL,
  CONSTRAINT UQ_BRZ_ORDERS_ROW UNIQUE
    (INGESTION_BATCH_ID, DATASET_RUN_ID, RECORD_HASH, SOURCE_ROW_NUMBER)
)
COMMENT = 'Immutable private Olist order rows with canonical lineage';

CREATE TABLE IF NOT EXISTS REVIEWLENS.BRONZE.BRZ_OLIST_PRODUCTS_RAW (
  PRODUCT_ID VARCHAR NOT NULL,
  PRODUCT_CATEGORY_NAME VARCHAR,
  PRODUCT_NAME_LENGHT NUMBER(38, 0),
  PRODUCT_DESCRIPTION_LENGHT NUMBER(38, 0),
  PRODUCT_PHOTOS_QTY NUMBER(38, 0),
  PRODUCT_WEIGHT_G NUMBER(38, 18),
  PRODUCT_LENGTH_CM NUMBER(38, 18),
  PRODUCT_HEIGHT_CM NUMBER(38, 18),
  PRODUCT_WIDTH_CM NUMBER(38, 18),
  SOURCE_RELEASE_ID VARCHAR NOT NULL,
  INGESTION_BATCH_ID VARCHAR NOT NULL,
  DATASET_RUN_ID VARCHAR NOT NULL,
  SOURCE_FILE_NAME VARCHAR NOT NULL,
  SOURCE_ROW_NUMBER NUMBER(38, 0) NOT NULL,
  SOURCE_OBJECT_SHA256 VARCHAR(64) NOT NULL,
  RECORD_HASH VARCHAR(64) NOT NULL,
  INGESTED_AT TIMESTAMP_TZ(6) NOT NULL,
  SCHEMA_VERSION VARCHAR NOT NULL,
  RAW_PAYLOAD VARCHAR NOT NULL,
  CONSTRAINT UQ_BRZ_PRODUCTS_ROW UNIQUE
    (INGESTION_BATCH_ID, DATASET_RUN_ID, RECORD_HASH, SOURCE_ROW_NUMBER)
)
COMMENT = 'Immutable private Olist product rows with canonical lineage';

CREATE TABLE IF NOT EXISTS REVIEWLENS.BRONZE.BRZ_OLIST_SELLERS_RAW (
  SELLER_ID VARCHAR NOT NULL,
  SELLER_ZIP_CODE_PREFIX VARCHAR NOT NULL,
  SELLER_CITY VARCHAR NOT NULL,
  SELLER_STATE VARCHAR NOT NULL,
  SOURCE_RELEASE_ID VARCHAR NOT NULL,
  INGESTION_BATCH_ID VARCHAR NOT NULL,
  DATASET_RUN_ID VARCHAR NOT NULL,
  SOURCE_FILE_NAME VARCHAR NOT NULL,
  SOURCE_ROW_NUMBER NUMBER(38, 0) NOT NULL,
  SOURCE_OBJECT_SHA256 VARCHAR(64) NOT NULL,
  RECORD_HASH VARCHAR(64) NOT NULL,
  INGESTED_AT TIMESTAMP_TZ(6) NOT NULL,
  SCHEMA_VERSION VARCHAR NOT NULL,
  RAW_PAYLOAD VARCHAR NOT NULL,
  CONSTRAINT UQ_BRZ_SELLERS_ROW UNIQUE
    (INGESTION_BATCH_ID, DATASET_RUN_ID, RECORD_HASH, SOURCE_ROW_NUMBER)
)
COMMENT = 'Immutable private Olist seller rows with canonical lineage';

CREATE TABLE IF NOT EXISTS REVIEWLENS.BRONZE.BRZ_PRODUCT_CATEGORY_TRANSLATION_RAW (
  PRODUCT_CATEGORY_NAME VARCHAR NOT NULL,
  PRODUCT_CATEGORY_NAME_ENGLISH VARCHAR NOT NULL,
  SOURCE_RELEASE_ID VARCHAR NOT NULL,
  INGESTION_BATCH_ID VARCHAR NOT NULL,
  DATASET_RUN_ID VARCHAR NOT NULL,
  SOURCE_FILE_NAME VARCHAR NOT NULL,
  SOURCE_ROW_NUMBER NUMBER(38, 0) NOT NULL,
  SOURCE_OBJECT_SHA256 VARCHAR(64) NOT NULL,
  RECORD_HASH VARCHAR(64) NOT NULL,
  INGESTED_AT TIMESTAMP_TZ(6) NOT NULL,
  SCHEMA_VERSION VARCHAR NOT NULL,
  RAW_PAYLOAD VARCHAR NOT NULL,
  CONSTRAINT UQ_BRZ_CATEGORY_TRANSLATION_ROW UNIQUE
    (INGESTION_BATCH_ID, DATASET_RUN_ID, RECORD_HASH, SOURCE_ROW_NUMBER)
)
COMMENT = 'Immutable Olist category translation rows with canonical lineage';

CREATE TABLE IF NOT EXISTS REVIEWLENS.AUDIT.BRONZE_LOAD_EVENT (
  EVENT_ID VARCHAR(64) NOT NULL,
  LEDGER_SCHEMA_VERSION NUMBER(10, 0) NOT NULL DEFAULT 1,
  SOURCE_RELEASE_ID VARCHAR NOT NULL,
  INGESTION_BATCH_ID VARCHAR NOT NULL,
  DATASET_RUN_ID VARCHAR NOT NULL,
  ATTEMPT_ID VARCHAR NOT NULL,
  DATASET_NAME VARCHAR NOT NULL,
  TARGET_TABLE VARCHAR NOT NULL,
  OBJECT_KEY VARCHAR NOT NULL,
  OBJECT_SHA256 VARCHAR(64) NOT NULL,
  QUERY_ID VARCHAR NOT NULL,
  STATUS VARCHAR NOT NULL,
  ROWS_PARSED NUMBER(38, 0) NOT NULL,
  ROWS_LOADED NUMBER(38, 0) NOT NULL,
  ERROR_COUNT NUMBER(38, 0) NOT NULL,
  EVENT_AT TIMESTAMP_TZ(6) NOT NULL,
  TRACE_ID VARCHAR NOT NULL,
  RECORDED_AT TIMESTAMP_TZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT PK_AUDIT_BRONZE_LOAD_EVENT PRIMARY KEY (EVENT_ID)
)
COMMENT = 'Append-only COPY result ledger containing identifiers/counts only';

GRANT USAGE ON FILE FORMAT REVIEWLENS.BRONZE.OLIST_PARQUET_FORMAT TO ROLE INGEST_ROLE;
GRANT INSERT ON ALL TABLES IN SCHEMA REVIEWLENS.BRONZE TO ROLE INGEST_ROLE;
REVOKE SELECT ON ALL TABLES IN SCHEMA REVIEWLENS.BRONZE FROM ROLE INGEST_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA REVIEWLENS.BRONZE TO ROLE TRANSFORMER_ROLE;
GRANT USAGE ON SCHEMA REVIEWLENS.AUDIT TO ROLE INGEST_ROLE;
GRANT SELECT, INSERT ON TABLE REVIEWLENS.AUDIT.BRONZE_LOAD_EVENT TO ROLE INGEST_ROLE;

CREATE VIEW IF NOT EXISTS REVIEWLENS.BRONZE.SCHEMA_COMPATIBILITY
COMMENT = 'Constant Bronze contract marker; querying it requires compute'
AS
SELECT
  'IMP-M2-013-BRONZE-V1'::VARCHAR AS MIGRATION_ID,
  1::NUMBER(10, 0) AS SCHEMA_VERSION,
  9::NUMBER(10, 0) AS DATASET_COUNT;
