-- ReviewLens M3 processing lineage and candidate physical-reference ledgers.
-- Secret-free, append-only and safe to re-run without resuming a warehouse.

USE ROLE ACCOUNTADMIN;
USE DATABASE REVIEWLENS;

CREATE TABLE IF NOT EXISTS REVIEWLENS.AUDIT.PROCESSING_RUN (
  PROCESS_RUN_ID VARCHAR(64) NOT NULL,
  LEDGER_SCHEMA_VERSION NUMBER(10, 0) NOT NULL DEFAULT 1,
  PROCESSING_CONTRACT_VERSION VARCHAR(128) NOT NULL,
  PHASE VARCHAR(16) NOT NULL,
  SOURCE_RELEASE_ID VARCHAR(80) NOT NULL,
  INGESTION_BATCH_ID VARCHAR(80) NOT NULL,
  INPUT_COUNT NUMBER(38, 0) NOT NULL,
  CREATED_AT TIMESTAMP_TZ(9) NOT NULL,
  TRACE_ID VARCHAR(128) NOT NULL,
  RECORDED_AT TIMESTAMP_TZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT PK_AUDIT_PROCESSING_RUN PRIMARY KEY (PROCESS_RUN_ID)
)
COMMENT = 'Immutable processing-run definition; producer enforces deterministic replay';

CREATE TABLE IF NOT EXISTS REVIEWLENS.AUDIT.PROCESSING_INPUT_REF (
  INPUT_REF_ID VARCHAR(64) NOT NULL,
  LEDGER_SCHEMA_VERSION NUMBER(10, 0) NOT NULL DEFAULT 1,
  PROCESS_RUN_ID VARCHAR(64) NOT NULL,
  INPUT_ORDINAL NUMBER(38, 0) NOT NULL,
  INPUT_KIND VARCHAR(32) NOT NULL,
  INPUT_LOGICAL_NAME VARCHAR(255) NOT NULL,
  INPUT_VERSION_ID VARCHAR(128) NOT NULL,
  PHYSICAL_DATABASE VARCHAR(255) NOT NULL,
  PHYSICAL_SCHEMA VARCHAR(255) NOT NULL,
  PHYSICAL_OBJECT VARCHAR(255) NOT NULL,
  CONTENT_SHA256 VARCHAR(64),
  CREATED_AT TIMESTAMP_TZ(9) NOT NULL,
  TRACE_ID VARCHAR(128) NOT NULL,
  RECORDED_AT TIMESTAMP_TZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT PK_AUDIT_PROCESSING_INPUT_REF PRIMARY KEY (INPUT_REF_ID),
  CONSTRAINT UQ_AUDIT_PROCESSING_INPUT_ORDINAL UNIQUE (PROCESS_RUN_ID, INPUT_ORDINAL)
)
COMMENT = 'Ordered 1:N immutable input lineage for a processing run; contains references only';

CREATE TABLE IF NOT EXISTS REVIEWLENS.AUDIT.CANDIDATE_PHYSICAL_REF_EVENT (
  REF_EVENT_ID VARCHAR(64) NOT NULL,
  LEDGER_SCHEMA_VERSION NUMBER(10, 0) NOT NULL DEFAULT 1,
  CANDIDATE_ID VARCHAR(64) NOT NULL,
  PROCESS_RUN_ID VARCHAR(64) NOT NULL,
  LAYER VARCHAR(16) NOT NULL,
  STRATEGY_VERSION VARCHAR(128) NOT NULL,
  LOGICAL_NAME VARCHAR(255) NOT NULL,
  PHYSICAL_DATABASE VARCHAR(255) NOT NULL,
  PHYSICAL_SCHEMA VARCHAR(255) NOT NULL,
  PHYSICAL_OBJECT VARCHAR(255) NOT NULL,
  STATE VARCHAR(32) NOT NULL,
  LEASE_OWNER VARCHAR(64),
  LEASE_EXPIRES_AT TIMESTAMP_TZ(9),
  EVENT_AT TIMESTAMP_TZ(9) NOT NULL,
  TRACE_ID VARCHAR(128) NOT NULL,
  RECORDED_AT TIMESTAMP_TZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT PK_AUDIT_CANDIDATE_PHYSICAL_REF_EVENT PRIMARY KEY (REF_EVENT_ID)
)
COMMENT = 'Append-only physical candidate reference and lifecycle events; no serving pointer mutation';

GRANT USAGE ON SCHEMA REVIEWLENS.AUDIT TO ROLE TRANSFORMER_ROLE;
GRANT SELECT, INSERT ON TABLE REVIEWLENS.AUDIT.PROCESSING_RUN TO ROLE TRANSFORMER_ROLE;
GRANT SELECT, INSERT ON TABLE REVIEWLENS.AUDIT.PROCESSING_INPUT_REF TO ROLE TRANSFORMER_ROLE;
GRANT SELECT, INSERT ON TABLE REVIEWLENS.AUDIT.CANDIDATE_PHYSICAL_REF_EVENT TO ROLE TRANSFORMER_ROLE;

GRANT USAGE ON SCHEMA REVIEWLENS.AUDIT TO ROLE GOLD_BUILDER_ROLE;
GRANT SELECT, INSERT ON TABLE REVIEWLENS.AUDIT.PROCESSING_RUN TO ROLE GOLD_BUILDER_ROLE;
GRANT SELECT, INSERT ON TABLE REVIEWLENS.AUDIT.PROCESSING_INPUT_REF TO ROLE GOLD_BUILDER_ROLE;
GRANT SELECT, INSERT ON TABLE REVIEWLENS.AUDIT.CANDIDATE_PHYSICAL_REF_EVENT TO ROLE GOLD_BUILDER_ROLE;

CREATE VIEW IF NOT EXISTS REVIEWLENS.AUDIT.M3_SCHEMA_COMPATIBILITY
COMMENT = 'Constant M3 processing-ledger contract marker; contains no source data'
AS
SELECT
  'IMP-M3-001-PROCESSING-V1'::VARCHAR(128) AS MIGRATION_ID,
  1::NUMBER(10, 0) AS SCHEMA_VERSION,
  3::NUMBER(10, 0) AS TABLE_COUNT;
