-- ReviewLens M3 immutable release definition and guarded CAS activation.
-- Safe to re-run; only the owner-executed versioned procedures may mutate the
-- one seeded active-pointer row.

USE ROLE ACCOUNTADMIN;
USE DATABASE REVIEWLENS;

CREATE TABLE IF NOT EXISTS REVIEWLENS.AUDIT.RELEASE_DEFINITION (
  RELEASE_ID VARCHAR(64) NOT NULL,
  DEFINITION_SHA256 VARCHAR(64) NOT NULL,
  DEFINITION_VERSION VARCHAR(128) NOT NULL,
  SOURCE_RELEASE_ID VARCHAR(80) NOT NULL,
  INGESTION_BATCH_ID VARCHAR(80) NOT NULL,
  SILVER_PROCESS_RUN_ID VARCHAR(64) NOT NULL,
  GOLD_PROCESS_RUN_ID VARCHAR(64) NOT NULL,
  SILVER_CANDIDATE_ID VARCHAR(64) NOT NULL,
  GOLD_CANDIDATE_ID VARCHAR(64) NOT NULL,
  SEMANTIC_CONTRACT_VERSION VARCHAR(128) NOT NULL,
  CREATED_AT TIMESTAMP_TZ(9) NOT NULL,
  TRACE_ID VARCHAR(128) NOT NULL,
  RECORDED_AT TIMESTAMP_TZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT PK_AUDIT_RELEASE_DEFINITION PRIMARY KEY (RELEASE_ID)
)
COMMENT = 'Immutable release header; only tested Silver/Gold candidate identities are recorded';

CREATE TABLE IF NOT EXISTS REVIEWLENS.AUDIT.RELEASE_OBJECT_REF (
  RELEASE_OBJECT_REF_ID VARCHAR(64) NOT NULL,
  RELEASE_ID VARCHAR(64) NOT NULL,
  LAYER VARCHAR(16) NOT NULL,
  LOGICAL_NAME VARCHAR(255) NOT NULL,
  PHYSICAL_DATABASE VARCHAR(255) NOT NULL,
  PHYSICAL_SCHEMA VARCHAR(255) NOT NULL,
  PHYSICAL_OBJECT VARCHAR(255) NOT NULL,
  CREATED_AT TIMESTAMP_TZ(9) NOT NULL,
  TRACE_ID VARCHAR(128) NOT NULL,
  RECORDED_AT TIMESTAMP_TZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT PK_AUDIT_RELEASE_OBJECT_REF PRIMARY KEY (RELEASE_OBJECT_REF_ID),
  CONSTRAINT UQ_AUDIT_RELEASE_OBJECT_REF UNIQUE (RELEASE_ID, LAYER, LOGICAL_NAME)
)
COMMENT = 'Immutable physical candidate references for one release definition; no serving aliases';

ALTER TABLE REVIEWLENS.AUDIT.RELEASE_EVENT
  ADD COLUMN IF NOT EXISTS EXPECTED_POINTER_VERSION NUMBER(38, 0);
ALTER TABLE REVIEWLENS.AUDIT.RELEASE_EVENT
  ADD COLUMN IF NOT EXISTS RESULT_POINTER_VERSION NUMBER(38, 0);
ALTER TABLE REVIEWLENS.AUDIT.RELEASE_EVENT
  ADD COLUMN IF NOT EXISTS DEFINITION_SHA256 VARCHAR(64);

-- Standard-table constraints are informational in Snowflake. Seeding exactly
-- one stable row lets versioned UPDATE perform a true row-level compare-and-set.
MERGE INTO REVIEWLENS.AUDIT.ACTIVE_RELEASE_POINTER AS pointer
USING (
  SELECT
    'ACTIVE_DATA_RELEASE'::VARCHAR(64) AS POINTER_NAME,
    '__UNINITIALIZED__'::VARCHAR(64) AS RELEASE_ID,
    '__UNINITIALIZED__'::VARCHAR(64) AS ACTIVATION_EVENT_ID,
    0::NUMBER(38, 0) AS POINTER_VERSION
) AS seed
ON pointer.POINTER_NAME = seed.POINTER_NAME
WHEN NOT MATCHED THEN INSERT (
  POINTER_NAME,
  LEDGER_SCHEMA_VERSION,
  RELEASE_ID,
  ACTIVATION_EVENT_ID,
  POINTER_VERSION,
  ACTIVATED_AT
) VALUES (
  seed.POINTER_NAME,
  1,
  seed.RELEASE_ID,
  seed.ACTIVATION_EVENT_ID,
  seed.POINTER_VERSION,
  CURRENT_TIMESTAMP()
);

CREATE PROCEDURE IF NOT EXISTS REVIEWLENS.AUDIT.ACTIVATE_RELEASE_V1(
  P_EXPECTED_POINTER_VERSION NUMBER(38, 0),
  P_TARGET_RELEASE_ID VARCHAR(64),
  P_EVENT_ID VARCHAR(64),
  P_ACTOR_SERVICE VARCHAR(128)
)
RETURNS VARIANT
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
  V_CURRENT_RELEASE_ID VARCHAR(64);
  V_CURRENT_POINTER_VERSION NUMBER(38, 0);
  V_ELIGIBLE_RELEASE_COUNT NUMBER(38, 0);
BEGIN
  BEGIN TRANSACTION;
  SELECT RELEASE_ID, POINTER_VERSION
    INTO :V_CURRENT_RELEASE_ID, :V_CURRENT_POINTER_VERSION
  FROM REVIEWLENS.AUDIT.ACTIVE_RELEASE_POINTER
  WHERE POINTER_NAME = 'ACTIVE_DATA_RELEASE';

  IF (V_CURRENT_RELEASE_ID = P_TARGET_RELEASE_ID)
     AND (V_CURRENT_POINTER_VERSION = P_EXPECTED_POINTER_VERSION + 1) THEN
    COMMIT;
    RETURN OBJECT_CONSTRUCT('status', 'REPLAY', 'pointer_version', V_CURRENT_POINTER_VERSION);
  END IF;
  IF V_CURRENT_POINTER_VERSION <> P_EXPECTED_POINTER_VERSION THEN
    ROLLBACK;
    RETURN OBJECT_CONSTRUCT('status', 'CAS_DENIED');
  END IF;

  SELECT COUNT(*) INTO :V_ELIGIBLE_RELEASE_COUNT
  FROM REVIEWLENS.AUDIT.RELEASE_DEFINITION AS definition
  WHERE definition.RELEASE_ID = P_TARGET_RELEASE_ID
    AND NOT EXISTS (
      SELECT 1
      FROM REVIEWLENS.AUDIT.RELEASE_EVENT AS terminal_event
      WHERE terminal_event.RELEASE_ID = definition.RELEASE_ID
        AND terminal_event.EVENT_TYPE IN ('INVALIDATED', 'REVOKED')
    );
  IF V_ELIGIBLE_RELEASE_COUNT <> 1 THEN
    ROLLBACK;
    RETURN OBJECT_CONSTRUCT('status', 'RELEASE_DENIED');
  END IF;

  INSERT INTO REVIEWLENS.AUDIT.RELEASE_EVENT (
    EVENT_ID, LEDGER_SCHEMA_VERSION, RELEASE_ID, DATASET_RUN_ID, EVENT_TYPE,
    PREVIOUS_RELEASE_ID, SILVER_VERSION, GOLD_VERSION, ACTOR_SERVICE,
    REASON_CODE, EXPECTED_POINTER_VERSION, RESULT_POINTER_VERSION,
    DEFINITION_SHA256, EVENT_AT, TRACE_ID, SANITIZED_METADATA
  )
  SELECT
    P_EVENT_ID, 1, definition.RELEASE_ID, definition.GOLD_PROCESS_RUN_ID,
    'ACTIVATED', NULLIF(V_CURRENT_RELEASE_ID, '__UNINITIALIZED__'),
    definition.SILVER_CANDIDATE_ID, definition.GOLD_CANDIDATE_ID,
    P_ACTOR_SERVICE, 'ACTIVATION_REQUESTED', P_EXPECTED_POINTER_VERSION,
    P_EXPECTED_POINTER_VERSION + 1, definition.DEFINITION_SHA256,
    CURRENT_TIMESTAMP(), CONCAT('m3-release:', SUBSTR(P_EVENT_ID, 1, 16)),
    OBJECT_CONSTRUCT('definition_sha256', definition.DEFINITION_SHA256)
  FROM REVIEWLENS.AUDIT.RELEASE_DEFINITION AS definition
  WHERE definition.RELEASE_ID = P_TARGET_RELEASE_ID;

  UPDATE REVIEWLENS.AUDIT.ACTIVE_RELEASE_POINTER
  SET RELEASE_ID = P_TARGET_RELEASE_ID,
      ACTIVATION_EVENT_ID = P_EVENT_ID,
      POINTER_VERSION = P_EXPECTED_POINTER_VERSION + 1,
      ACTIVATED_AT = CURRENT_TIMESTAMP(),
      UPDATED_AT = CURRENT_TIMESTAMP()
  WHERE POINTER_NAME = 'ACTIVE_DATA_RELEASE'
    AND POINTER_VERSION = P_EXPECTED_POINTER_VERSION;
  IF SQLROWCOUNT <> 1 THEN
    ROLLBACK;
    RETURN OBJECT_CONSTRUCT('status', 'CAS_DENIED');
  END IF;
  COMMIT;
  RETURN OBJECT_CONSTRUCT('status', 'ACTIVATED', 'pointer_version', P_EXPECTED_POINTER_VERSION + 1);
EXCEPTION
  WHEN OTHER THEN
    ROLLBACK;
    RAISE;
END;
$$;

CREATE PROCEDURE IF NOT EXISTS REVIEWLENS.AUDIT.ROLLBACK_RELEASE_V1(
  P_EXPECTED_POINTER_VERSION NUMBER(38, 0),
  P_TARGET_RELEASE_ID VARCHAR(64),
  P_EVENT_ID VARCHAR(64),
  P_ACTOR_SERVICE VARCHAR(128)
)
RETURNS VARIANT
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
  V_CURRENT_RELEASE_ID VARCHAR(64);
  V_CURRENT_POINTER_VERSION NUMBER(38, 0);
  V_ELIGIBLE_RELEASE_COUNT NUMBER(38, 0);
BEGIN
  BEGIN TRANSACTION;
  SELECT RELEASE_ID, POINTER_VERSION
    INTO :V_CURRENT_RELEASE_ID, :V_CURRENT_POINTER_VERSION
  FROM REVIEWLENS.AUDIT.ACTIVE_RELEASE_POINTER
  WHERE POINTER_NAME = 'ACTIVE_DATA_RELEASE';

  IF (V_CURRENT_RELEASE_ID = P_TARGET_RELEASE_ID)
     AND (V_CURRENT_POINTER_VERSION = P_EXPECTED_POINTER_VERSION + 1) THEN
    COMMIT;
    RETURN OBJECT_CONSTRUCT('status', 'REPLAY', 'pointer_version', V_CURRENT_POINTER_VERSION);
  END IF;
  IF V_CURRENT_POINTER_VERSION <> P_EXPECTED_POINTER_VERSION
     OR V_CURRENT_RELEASE_ID = '__UNINITIALIZED__'
     OR V_CURRENT_RELEASE_ID = P_TARGET_RELEASE_ID THEN
    ROLLBACK;
    RETURN OBJECT_CONSTRUCT('status', 'CAS_DENIED');
  END IF;

  SELECT COUNT(*) INTO :V_ELIGIBLE_RELEASE_COUNT
  FROM REVIEWLENS.AUDIT.RELEASE_DEFINITION AS definition
  WHERE definition.RELEASE_ID = P_TARGET_RELEASE_ID
    AND EXISTS (
      SELECT 1
      FROM REVIEWLENS.AUDIT.RELEASE_EVENT AS prior_event
      WHERE prior_event.RELEASE_ID = definition.RELEASE_ID
        AND prior_event.EVENT_TYPE IN ('ACTIVATED', 'ROLLED_BACK')
    )
    AND NOT EXISTS (
      SELECT 1
      FROM REVIEWLENS.AUDIT.RELEASE_EVENT AS terminal_event
      WHERE terminal_event.RELEASE_ID = definition.RELEASE_ID
        AND terminal_event.EVENT_TYPE IN ('INVALIDATED', 'REVOKED')
    );
  IF V_ELIGIBLE_RELEASE_COUNT <> 1 THEN
    ROLLBACK;
    RETURN OBJECT_CONSTRUCT('status', 'RELEASE_DENIED');
  END IF;

  INSERT INTO REVIEWLENS.AUDIT.RELEASE_EVENT (
    EVENT_ID, LEDGER_SCHEMA_VERSION, RELEASE_ID, DATASET_RUN_ID, EVENT_TYPE,
    PREVIOUS_RELEASE_ID, SILVER_VERSION, GOLD_VERSION, ACTOR_SERVICE,
    REASON_CODE, EXPECTED_POINTER_VERSION, RESULT_POINTER_VERSION,
    DEFINITION_SHA256, EVENT_AT, TRACE_ID, SANITIZED_METADATA
  )
  SELECT
    P_EVENT_ID, 1, definition.RELEASE_ID, definition.GOLD_PROCESS_RUN_ID,
    'ROLLED_BACK', V_CURRENT_RELEASE_ID,
    definition.SILVER_CANDIDATE_ID, definition.GOLD_CANDIDATE_ID,
    P_ACTOR_SERVICE, 'ROLLBACK_REQUESTED', P_EXPECTED_POINTER_VERSION,
    P_EXPECTED_POINTER_VERSION + 1, definition.DEFINITION_SHA256,
    CURRENT_TIMESTAMP(), CONCAT('m3-release:', SUBSTR(P_EVENT_ID, 1, 16)),
    OBJECT_CONSTRUCT('definition_sha256', definition.DEFINITION_SHA256)
  FROM REVIEWLENS.AUDIT.RELEASE_DEFINITION AS definition
  WHERE definition.RELEASE_ID = P_TARGET_RELEASE_ID;

  UPDATE REVIEWLENS.AUDIT.ACTIVE_RELEASE_POINTER
  SET RELEASE_ID = P_TARGET_RELEASE_ID,
      ACTIVATION_EVENT_ID = P_EVENT_ID,
      POINTER_VERSION = P_EXPECTED_POINTER_VERSION + 1,
      ACTIVATED_AT = CURRENT_TIMESTAMP(),
      UPDATED_AT = CURRENT_TIMESTAMP()
  WHERE POINTER_NAME = 'ACTIVE_DATA_RELEASE'
    AND POINTER_VERSION = P_EXPECTED_POINTER_VERSION;
  IF SQLROWCOUNT <> 1 THEN
    ROLLBACK;
    RETURN OBJECT_CONSTRUCT('status', 'CAS_DENIED');
  END IF;
  COMMIT;
  RETURN OBJECT_CONSTRUCT('status', 'ROLLED_BACK', 'pointer_version', P_EXPECTED_POINTER_VERSION + 1);
EXCEPTION
  WHEN OTHER THEN
    ROLLBACK;
    RAISE;
END;
$$;

GRANT USAGE ON SCHEMA REVIEWLENS.AUDIT TO ROLE GOLD_BUILDER_ROLE;
GRANT SELECT, INSERT ON TABLE REVIEWLENS.AUDIT.RELEASE_DEFINITION TO ROLE GOLD_BUILDER_ROLE;
GRANT SELECT, INSERT ON TABLE REVIEWLENS.AUDIT.RELEASE_OBJECT_REF TO ROLE GOLD_BUILDER_ROLE;
GRANT SELECT, INSERT ON TABLE REVIEWLENS.AUDIT.RELEASE_EVENT TO ROLE GOLD_BUILDER_ROLE;
GRANT EXECUTE ON PROCEDURE REVIEWLENS.AUDIT.ACTIVATE_RELEASE_V1(NUMBER, VARCHAR, VARCHAR, VARCHAR)
  TO ROLE GOLD_BUILDER_ROLE;
GRANT EXECUTE ON PROCEDURE REVIEWLENS.AUDIT.ROLLBACK_RELEASE_V1(NUMBER, VARCHAR, VARCHAR, VARCHAR)
  TO ROLE GOLD_BUILDER_ROLE;

CREATE VIEW IF NOT EXISTS REVIEWLENS.AUDIT.M3_RELEASE_SCHEMA_COMPATIBILITY
COMMENT = 'Constant M3 atomic-release contract marker; contains no source records'
AS
SELECT
  'IMP-M3-018-ATOMIC-RELEASE-V1'::VARCHAR(128) AS MIGRATION_ID,
  1::NUMBER(10, 0) AS SCHEMA_VERSION,
  2::NUMBER(10, 0) AS TABLE_COUNT,
  2::NUMBER(10, 0) AS PROCEDURE_COUNT;
