-- ReviewLens M3 release activation integrity gate.
-- Apply only after 007_atomic_release.sql. This additive migration replaces the
-- guarded procedures so a header alone can never become an active release.

USE ROLE ACCOUNTADMIN;
USE DATABASE REVIEWLENS;

CREATE OR REPLACE VIEW REVIEWLENS.AUDIT.M3_RELEASE_ACTIVATION_ELIGIBILITY
COMMENT = 'Aggregate-only integrity gate for complete tested immutable M3 releases'
AS
WITH expected_ref AS (
  SELECT COLUMN1::VARCHAR(16) AS LAYER, COLUMN2::VARCHAR(255) AS LOGICAL_NAME
  FROM VALUES
    ('SILVER', 'SIL_CATEGORY_TRANSLATION'),
    ('SILVER', 'SIL_CUSTOMER'),
    ('SILVER', 'SIL_GEOLOCATION_ZIP'),
    ('SILVER', 'SIL_ORDER'),
    ('SILVER', 'SIL_ORDER_ITEM'),
    ('SILVER', 'SIL_ORDER_PAYMENT'),
    ('SILVER', 'SIL_ORDER_REVIEW'),
    ('SILVER', 'SIL_PRODUCT'),
    ('SILVER', 'SIL_SELLER'),
    ('SILVER', 'SIL_UNKNOWN_MEMBER_REGISTRY'),
    ('GOLD', 'BRIDGE_REVIEW_ITEM_ATTRIBUTION'),
    ('GOLD', 'DIM_CUSTOMER'),
    ('GOLD', 'DIM_DATE'),
    ('GOLD', 'DIM_GEOGRAPHY'),
    ('GOLD', 'DIM_PRODUCT'),
    ('GOLD', 'DIM_SELLER'),
    ('GOLD', 'FACT_ORDER'),
    ('GOLD', 'FACT_ORDER_ITEM'),
    ('GOLD', 'FACT_PAYMENT'),
    ('GOLD', 'FACT_REVIEW_BASE'),
    ('GOLD', 'MART_CUSTOMER_OVERVIEW'),
    ('GOLD', 'MART_ORDER_DELIVERY'),
    ('GOLD', 'MART_PRODUCT_REVIEW'),
    ('GOLD', 'MART_SELLER_PERFORMANCE'),
    ('GOLD', 'SEM_CUSTOMER_OVERVIEW'),
    ('GOLD', 'SEM_ORDER_DELIVERY'),
    ('GOLD', 'SEM_PRODUCT_REVIEW'),
    ('GOLD', 'SEM_SELLER_PERFORMANCE')
),
latest_candidate_ref AS (
  SELECT
    CANDIDATE_ID,
    LAYER,
    PROCESS_RUN_ID,
    LOGICAL_NAME,
    PHYSICAL_DATABASE,
    PHYSICAL_SCHEMA,
    PHYSICAL_OBJECT,
    STATE,
    ROW_NUMBER() OVER (
      PARTITION BY CANDIDATE_ID, LAYER, PHYSICAL_DATABASE, PHYSICAL_SCHEMA, PHYSICAL_OBJECT
      ORDER BY EVENT_AT DESC, REF_EVENT_ID DESC
    ) AS EVENT_RANK
  FROM REVIEWLENS.AUDIT.CANDIDATE_PHYSICAL_REF_EVENT
)
SELECT
  definition.RELEASE_ID,
  (
    SELECT COUNT(*)
    FROM REVIEWLENS.AUDIT.RELEASE_OBJECT_REF AS all_ref
    WHERE all_ref.RELEASE_ID = definition.RELEASE_ID
  ) AS OBJECT_REF_COUNT,
  COUNT(ref.RELEASE_OBJECT_REF_ID) AS MATCHED_EXPECTED_REF_COUNT,
  COUNT_IF(latest.STATE = 'TEST_PASSED') AS TEST_PASSED_EXPECTED_REF_COUNT
FROM REVIEWLENS.AUDIT.RELEASE_DEFINITION AS definition
CROSS JOIN expected_ref AS expected
LEFT JOIN REVIEWLENS.AUDIT.RELEASE_OBJECT_REF AS ref
  ON ref.RELEASE_ID = definition.RELEASE_ID
  AND ref.LAYER = expected.LAYER
  AND ref.LOGICAL_NAME = expected.LOGICAL_NAME
LEFT JOIN latest_candidate_ref AS latest
  ON latest.EVENT_RANK = 1
  AND latest.LAYER = expected.LAYER
  AND latest.LOGICAL_NAME = expected.LOGICAL_NAME
  AND latest.CANDIDATE_ID = IFF(
    expected.LAYER = 'SILVER', definition.SILVER_CANDIDATE_ID, definition.GOLD_CANDIDATE_ID
  )
  AND latest.PROCESS_RUN_ID = IFF(
    expected.LAYER = 'SILVER', definition.SILVER_PROCESS_RUN_ID, definition.GOLD_PROCESS_RUN_ID
  )
  AND latest.PHYSICAL_DATABASE = ref.PHYSICAL_DATABASE
  AND latest.PHYSICAL_SCHEMA = ref.PHYSICAL_SCHEMA
  AND latest.PHYSICAL_OBJECT = ref.PHYSICAL_OBJECT
GROUP BY definition.RELEASE_ID;

CREATE OR REPLACE PROCEDURE REVIEWLENS.AUDIT.ACTIVATE_RELEASE_V1(
  P_EXPECTED_POINTER_VERSION NUMBER(38, 0),
  P_TARGET_RELEASE_ID VARCHAR(64),
  P_EVENT_ID VARCHAR(64),
  P_ACTOR_SERVICE VARCHAR(128)
)
RETURNS VARIANT
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
  V_CURRENT_RELEASE_ID VARCHAR(64);
  V_CURRENT_POINTER_VERSION NUMBER(38, 0);
  V_ELIGIBLE_RELEASE_COUNT NUMBER(38, 0);
BEGIN
  BEGIN TRANSACTION;
  SELECT RELEASE_ID, POINTER_VERSION
    INTO :V_CURRENT_RELEASE_ID, :V_CURRENT_POINTER_VERSION
  FROM REVIEWLENS.AUDIT.ACTIVE_RELEASE_POINTER
  WHERE POINTER_NAME = 'ACTIVE_DATA_RELEASE';

  IF (
    (V_CURRENT_RELEASE_ID = P_TARGET_RELEASE_ID)
    AND (V_CURRENT_POINTER_VERSION = P_EXPECTED_POINTER_VERSION + 1)
  ) THEN
    COMMIT;
    RETURN OBJECT_CONSTRUCT('status', 'REPLAY', 'pointer_version', V_CURRENT_POINTER_VERSION);
  END IF;
  IF (V_CURRENT_POINTER_VERSION <> P_EXPECTED_POINTER_VERSION) THEN
    ROLLBACK;
    RETURN OBJECT_CONSTRUCT('status', 'CAS_DENIED');
  END IF;

  SELECT COUNT(*) INTO :V_ELIGIBLE_RELEASE_COUNT
  FROM REVIEWLENS.AUDIT.RELEASE_DEFINITION AS definition
  INNER JOIN REVIEWLENS.AUDIT.M3_RELEASE_ACTIVATION_ELIGIBILITY AS eligibility
    ON eligibility.RELEASE_ID = definition.RELEASE_ID
  WHERE definition.RELEASE_ID = :P_TARGET_RELEASE_ID
    AND eligibility.OBJECT_REF_COUNT = 28
    AND eligibility.MATCHED_EXPECTED_REF_COUNT = 28
    AND eligibility.TEST_PASSED_EXPECTED_REF_COUNT = 28
    AND EXISTS (
      SELECT 1
      FROM REVIEWLENS.AUDIT.RELEASE_EVENT AS created_event
      WHERE created_event.RELEASE_ID = definition.RELEASE_ID
        AND created_event.EVENT_TYPE = 'CREATED'
        AND created_event.DATASET_RUN_ID = definition.GOLD_PROCESS_RUN_ID
        AND created_event.SILVER_VERSION = definition.SILVER_CANDIDATE_ID
        AND created_event.GOLD_VERSION = definition.GOLD_CANDIDATE_ID
        AND created_event.DEFINITION_SHA256 = definition.DEFINITION_SHA256
    )
    AND NOT EXISTS (
      SELECT 1
      FROM REVIEWLENS.AUDIT.RELEASE_EVENT AS terminal_event
      WHERE terminal_event.RELEASE_ID = definition.RELEASE_ID
        AND terminal_event.EVENT_TYPE IN ('INVALIDATED', 'REVOKED')
    );
  IF (V_ELIGIBLE_RELEASE_COUNT <> 1) THEN
    ROLLBACK;
    RETURN OBJECT_CONSTRUCT('status', 'RELEASE_DENIED');
  END IF;

  INSERT INTO REVIEWLENS.AUDIT.RELEASE_EVENT (
    EVENT_ID, LEDGER_SCHEMA_VERSION, RELEASE_ID, DATASET_RUN_ID, EVENT_TYPE,
    PREVIOUS_RELEASE_ID, SILVER_VERSION, GOLD_VERSION, ACTOR_SERVICE,
    REASON_CODE, EXPECTED_POINTER_VERSION, RESULT_POINTER_VERSION,
    DEFINITION_SHA256, EVENT_AT, TRACE_ID, SANITIZED_METADATA
  )
  SELECT
    :P_EVENT_ID, 1, definition.RELEASE_ID, definition.GOLD_PROCESS_RUN_ID,
    'ACTIVATED', NULLIF(:V_CURRENT_RELEASE_ID, '__UNINITIALIZED__'),
    definition.SILVER_CANDIDATE_ID, definition.GOLD_CANDIDATE_ID,
    :P_ACTOR_SERVICE, 'ACTIVATION_REQUESTED', :P_EXPECTED_POINTER_VERSION,
    :P_EXPECTED_POINTER_VERSION + 1, definition.DEFINITION_SHA256,
    CURRENT_TIMESTAMP(), CONCAT('m3-release:', SUBSTR(:P_EVENT_ID, 1, 16)),
    OBJECT_CONSTRUCT('definition_sha256', definition.DEFINITION_SHA256)
  FROM REVIEWLENS.AUDIT.RELEASE_DEFINITION AS definition
  WHERE definition.RELEASE_ID = :P_TARGET_RELEASE_ID;

  UPDATE REVIEWLENS.AUDIT.ACTIVE_RELEASE_POINTER
  SET RELEASE_ID = :P_TARGET_RELEASE_ID,
      ACTIVATION_EVENT_ID = :P_EVENT_ID,
      POINTER_VERSION = :P_EXPECTED_POINTER_VERSION + 1,
      ACTIVATED_AT = CURRENT_TIMESTAMP(),
      UPDATED_AT = CURRENT_TIMESTAMP()
  WHERE POINTER_NAME = 'ACTIVE_DATA_RELEASE'
    AND POINTER_VERSION = :P_EXPECTED_POINTER_VERSION;
  IF (SQLROWCOUNT <> 1) THEN
    ROLLBACK;
    RETURN OBJECT_CONSTRUCT('status', 'CAS_DENIED');
  END IF;
  COMMIT;
  RETURN OBJECT_CONSTRUCT('status', 'ACTIVATED', 'pointer_version', P_EXPECTED_POINTER_VERSION + 1);
EXCEPTION
  WHEN OTHER THEN
    ROLLBACK;
    RAISE;
END;
$$;

CREATE OR REPLACE PROCEDURE REVIEWLENS.AUDIT.ROLLBACK_RELEASE_V1(
  P_EXPECTED_POINTER_VERSION NUMBER(38, 0),
  P_TARGET_RELEASE_ID VARCHAR(64),
  P_EVENT_ID VARCHAR(64),
  P_ACTOR_SERVICE VARCHAR(128)
)
RETURNS VARIANT
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
  V_CURRENT_RELEASE_ID VARCHAR(64);
  V_CURRENT_POINTER_VERSION NUMBER(38, 0);
  V_ELIGIBLE_RELEASE_COUNT NUMBER(38, 0);
BEGIN
  BEGIN TRANSACTION;
  SELECT RELEASE_ID, POINTER_VERSION
    INTO :V_CURRENT_RELEASE_ID, :V_CURRENT_POINTER_VERSION
  FROM REVIEWLENS.AUDIT.ACTIVE_RELEASE_POINTER
  WHERE POINTER_NAME = 'ACTIVE_DATA_RELEASE';

  IF (
    (V_CURRENT_RELEASE_ID = P_TARGET_RELEASE_ID)
    AND (V_CURRENT_POINTER_VERSION = P_EXPECTED_POINTER_VERSION + 1)
  ) THEN
    COMMIT;
    RETURN OBJECT_CONSTRUCT('status', 'REPLAY', 'pointer_version', V_CURRENT_POINTER_VERSION);
  END IF;
  IF (
    V_CURRENT_POINTER_VERSION <> P_EXPECTED_POINTER_VERSION
    OR V_CURRENT_RELEASE_ID = '__UNINITIALIZED__'
    OR V_CURRENT_RELEASE_ID = P_TARGET_RELEASE_ID
  ) THEN
    ROLLBACK;
    RETURN OBJECT_CONSTRUCT('status', 'CAS_DENIED');
  END IF;

  SELECT COUNT(*) INTO :V_ELIGIBLE_RELEASE_COUNT
  FROM REVIEWLENS.AUDIT.RELEASE_DEFINITION AS definition
  INNER JOIN REVIEWLENS.AUDIT.M3_RELEASE_ACTIVATION_ELIGIBILITY AS eligibility
    ON eligibility.RELEASE_ID = definition.RELEASE_ID
  WHERE definition.RELEASE_ID = :P_TARGET_RELEASE_ID
    AND eligibility.OBJECT_REF_COUNT = 28
    AND eligibility.MATCHED_EXPECTED_REF_COUNT = 28
    AND eligibility.TEST_PASSED_EXPECTED_REF_COUNT = 28
    AND EXISTS (
      SELECT 1
      FROM REVIEWLENS.AUDIT.RELEASE_EVENT AS created_event
      WHERE created_event.RELEASE_ID = definition.RELEASE_ID
        AND created_event.EVENT_TYPE = 'CREATED'
        AND created_event.DATASET_RUN_ID = definition.GOLD_PROCESS_RUN_ID
        AND created_event.SILVER_VERSION = definition.SILVER_CANDIDATE_ID
        AND created_event.GOLD_VERSION = definition.GOLD_CANDIDATE_ID
        AND created_event.DEFINITION_SHA256 = definition.DEFINITION_SHA256
    )
    AND EXISTS (
      SELECT 1
      FROM REVIEWLENS.AUDIT.RELEASE_EVENT AS prior_event
      WHERE prior_event.RELEASE_ID = definition.RELEASE_ID
        AND prior_event.EVENT_TYPE IN ('ACTIVATED', 'ROLLED_BACK')
    )
    AND NOT EXISTS (
      SELECT 1
      FROM REVIEWLENS.AUDIT.RELEASE_EVENT AS terminal_event
      WHERE terminal_event.RELEASE_ID = definition.RELEASE_ID
        AND terminal_event.EVENT_TYPE IN ('INVALIDATED', 'REVOKED')
    );
  IF (V_ELIGIBLE_RELEASE_COUNT <> 1) THEN
    ROLLBACK;
    RETURN OBJECT_CONSTRUCT('status', 'RELEASE_DENIED');
  END IF;

  INSERT INTO REVIEWLENS.AUDIT.RELEASE_EVENT (
    EVENT_ID, LEDGER_SCHEMA_VERSION, RELEASE_ID, DATASET_RUN_ID, EVENT_TYPE,
    PREVIOUS_RELEASE_ID, SILVER_VERSION, GOLD_VERSION, ACTOR_SERVICE,
    REASON_CODE, EXPECTED_POINTER_VERSION, RESULT_POINTER_VERSION,
    DEFINITION_SHA256, EVENT_AT, TRACE_ID, SANITIZED_METADATA
  )
  SELECT
    :P_EVENT_ID, 1, definition.RELEASE_ID, definition.GOLD_PROCESS_RUN_ID,
    'ROLLED_BACK', :V_CURRENT_RELEASE_ID,
    definition.SILVER_CANDIDATE_ID, definition.GOLD_CANDIDATE_ID,
    :P_ACTOR_SERVICE, 'ROLLBACK_REQUESTED', :P_EXPECTED_POINTER_VERSION,
    :P_EXPECTED_POINTER_VERSION + 1, definition.DEFINITION_SHA256,
    CURRENT_TIMESTAMP(), CONCAT('m3-release:', SUBSTR(:P_EVENT_ID, 1, 16)),
    OBJECT_CONSTRUCT('definition_sha256', definition.DEFINITION_SHA256)
  FROM REVIEWLENS.AUDIT.RELEASE_DEFINITION AS definition
  WHERE definition.RELEASE_ID = :P_TARGET_RELEASE_ID;

  UPDATE REVIEWLENS.AUDIT.ACTIVE_RELEASE_POINTER
  SET RELEASE_ID = :P_TARGET_RELEASE_ID,
      ACTIVATION_EVENT_ID = :P_EVENT_ID,
      POINTER_VERSION = :P_EXPECTED_POINTER_VERSION + 1,
      ACTIVATED_AT = CURRENT_TIMESTAMP(),
      UPDATED_AT = CURRENT_TIMESTAMP()
  WHERE POINTER_NAME = 'ACTIVE_DATA_RELEASE'
    AND POINTER_VERSION = :P_EXPECTED_POINTER_VERSION;
  IF (SQLROWCOUNT <> 1) THEN
    ROLLBACK;
    RETURN OBJECT_CONSTRUCT('status', 'CAS_DENIED');
  END IF;
  COMMIT;
  RETURN OBJECT_CONSTRUCT('status', 'ROLLED_BACK', 'pointer_version', P_EXPECTED_POINTER_VERSION + 1);
EXCEPTION
  WHEN OTHER THEN
    ROLLBACK;
    RAISE;
END;
$$;

GRANT SELECT ON VIEW REVIEWLENS.AUDIT.M3_RELEASE_ACTIVATION_ELIGIBILITY TO ROLE GOLD_BUILDER_ROLE;

CREATE OR REPLACE VIEW REVIEWLENS.AUDIT.M3_RELEASE_ACTIVATION_INTEGRITY_COMPATIBILITY
COMMENT = 'Constant M3 release-activation integrity contract marker; contains no source records'
AS
SELECT
  'IMP-M3-018-RELEASE-INTEGRITY-V1'::VARCHAR(128) AS MIGRATION_ID,
  28::NUMBER(10, 0) AS EXPECTED_OBJECT_REF_COUNT,
  2::NUMBER(10, 0) AS PROCEDURE_COUNT;
