-- ReviewLens M4 append-only enrichment ledger contract.
-- This migration contains metadata/hash fields only: never review text, prompt
-- text, response bodies, natural IDs, credentials, payment values or embeddings.

USE ROLE ACCOUNTADMIN;
USE DATABASE REVIEWLENS;

CREATE TABLE IF NOT EXISTS REVIEWLENS.AUDIT.AI_ENRICHMENT_RUN (
  ENRICHMENT_RUN_ID VARCHAR(64) NOT NULL,
  LEDGER_SCHEMA_VERSION NUMBER(10, 0) NOT NULL DEFAULT 1,
  SOURCE_RELEASE_ID VARCHAR(80) NOT NULL,
  ENRICHMENT_VERSION VARCHAR(64) NOT NULL,
  SELECTION_SHA256 VARCHAR(64) NOT NULL,
  STATE VARCHAR(32) NOT NULL,
  TRACE_ID VARCHAR(128) NOT NULL,
  CREATED_AT TIMESTAMP_TZ(9) NOT NULL,
  RECORDED_AT TIMESTAMP_TZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT PK_AUDIT_AI_ENRICHMENT_RUN PRIMARY KEY (ENRICHMENT_RUN_ID)
)
COMMENT = 'Append-only M4 enrichment run ledger; source references and hashes only';

CREATE TABLE IF NOT EXISTS REVIEWLENS.AUDIT.AI_ENRICHMENT_INVOCATION (
  INVOCATION_ID VARCHAR(64) NOT NULL,
  LEDGER_SCHEMA_VERSION NUMBER(10, 0) NOT NULL DEFAULT 1,
  ENRICHMENT_RUN_ID VARCHAR(64) NOT NULL,
  SOURCE_RECORD_HASH VARCHAR(64) NOT NULL,
  INPUT_SHA256 VARCHAR(64) NOT NULL,
  ATTEMPT_NUMBER NUMBER(10, 0) NOT NULL,
  STATE VARCHAR(32) NOT NULL,
  MODEL_ID VARCHAR(256) NOT NULL,
  PROMPT_VERSION VARCHAR(128) NOT NULL,
  OUTPUT_SCHEMA_VERSION VARCHAR(128) NOT NULL,
  TAXONOMY_VERSION VARCHAR(128) NOT NULL,
  PROVIDER_POLICY_VERSION VARCHAR(128) NOT NULL,
  INPUT_TOKEN_COUNT NUMBER(38, 0) NOT NULL DEFAULT 0,
  OUTPUT_TOKEN_COUNT NUMBER(38, 0) NOT NULL DEFAULT 0,
  COST_USD NUMBER(18, 8) NOT NULL DEFAULT 0,
  LATENCY_MS NUMBER(38, 0),
  SANITIZED_ERROR_CODE VARCHAR(128),
  TRACE_ID VARCHAR(128) NOT NULL,
  CREATED_AT TIMESTAMP_TZ(9) NOT NULL,
  RECORDED_AT TIMESTAMP_TZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT PK_AUDIT_AI_ENRICHMENT_INVOCATION PRIMARY KEY (INVOCATION_ID)
)
COMMENT = 'Append-only M4 enrichment attempt ledger; no external payload body is stored';

CREATE TABLE IF NOT EXISTS REVIEWLENS.AUDIT.AI_ENRICHMENT_RESULT_MAP (
  RESULT_MAP_ID VARCHAR(64) NOT NULL,
  LEDGER_SCHEMA_VERSION NUMBER(10, 0) NOT NULL DEFAULT 1,
  ENRICHMENT_RUN_ID VARCHAR(64) NOT NULL,
  SOURCE_RECORD_HASH VARCHAR(64) NOT NULL,
  ENRICHMENT_VERSION VARCHAR(64) NOT NULL,
  INVOCATION_ID VARCHAR(64) NOT NULL,
  RESULT_SHA256 VARCHAR(64) NOT NULL,
  STATE VARCHAR(32) NOT NULL,
  TRACE_ID VARCHAR(128) NOT NULL,
  CREATED_AT TIMESTAMP_TZ(9) NOT NULL,
  RECORDED_AT TIMESTAMP_TZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT PK_AUDIT_AI_ENRICHMENT_RESULT_MAP PRIMARY KEY (RESULT_MAP_ID),
  CONSTRAINT UQ_AUDIT_AI_ENRICHMENT_RESULT_VERSION UNIQUE (
    SOURCE_RECORD_HASH, ENRICHMENT_VERSION
  )
)
COMMENT = 'Validated enrichment result references only; AI result fields are committed later';

GRANT USAGE ON SCHEMA REVIEWLENS.AUDIT TO ROLE AI_ENRICH_ROLE;
GRANT SELECT, INSERT ON TABLE REVIEWLENS.AUDIT.AI_ENRICHMENT_RUN TO ROLE AI_ENRICH_ROLE;
GRANT SELECT, INSERT ON TABLE REVIEWLENS.AUDIT.AI_ENRICHMENT_INVOCATION TO ROLE AI_ENRICH_ROLE;
GRANT SELECT, INSERT ON TABLE REVIEWLENS.AUDIT.AI_ENRICHMENT_RESULT_MAP TO ROLE AI_ENRICH_ROLE;

CREATE VIEW IF NOT EXISTS REVIEWLENS.AUDIT.M4_ENRICHMENT_SCHEMA_COMPATIBILITY
COMMENT = 'Constant M4 AI enrichment ledger contract marker; contains no source data'
AS
SELECT
  'IMP-M4-002-ENRICHMENT-LEDGERS-V1'::VARCHAR(128) AS MIGRATION_ID,
  1::NUMBER(10, 0) AS SCHEMA_VERSION,
  3::NUMBER(10, 0) AS TABLE_COUNT;
