-- ReviewLens M4 private committed enrichment contract.
-- This table is not an audit ledger: it stores validated serving data only.
-- It is private and never receives source review text, prompts, raw provider
-- responses, credentials, payment values or vector payloads.

USE ROLE ACCOUNTADMIN;
USE DATABASE REVIEWLENS;

CREATE TABLE IF NOT EXISTS REVIEWLENS.AI.AI_REVIEW_ENRICHED (
  REVIEW_ID VARCHAR(128) NOT NULL,
  ORDER_ID VARCHAR(128) NOT NULL,
  REVIEW_LINEAGE_SHA256 VARCHAR(64) NOT NULL,
  SOURCE_RECORD_HASH VARCHAR(64) NOT NULL,
  ENRICHMENT_VERSION VARCHAR(64) NOT NULL,
  INPUT_SHA256 VARCHAR(64) NOT NULL,
  RESULT_MAP_ID VARCHAR(64) NOT NULL,
  RESULT_SHA256 VARCHAR(64) NOT NULL,
  MODEL_ID VARCHAR(256) NOT NULL,
  PROMPT_VERSION VARCHAR(128) NOT NULL,
  OUTPUT_SCHEMA_VERSION VARCHAR(128) NOT NULL,
  TAXONOMY_VERSION VARCHAR(128) NOT NULL,
  DLP_POLICY_VERSION VARCHAR(128) NOT NULL,
  SENTIMENT VARCHAR(16) NOT NULL,
  CONFIDENCE NUMBER(6, 5) NOT NULL,
  ASPECT_SENTIMENTS ARRAY NOT NULL,
  TOPICS ARRAY NOT NULL,
  SUMMARY VARCHAR(500) NOT NULL,
  HIGHLIGHTS ARRAY NOT NULL,
  STATUS VARCHAR(32) NOT NULL DEFAULT 'VALID',
  CREATED_AT TIMESTAMP_TZ(9) NOT NULL,
  UPDATED_AT TIMESTAMP_TZ(9) NOT NULL,
  CONSTRAINT PK_AI_REVIEW_ENRICHED PRIMARY KEY (REVIEW_ID, ORDER_ID, ENRICHMENT_VERSION),
  CONSTRAINT UQ_AI_REVIEW_ENRICHED_LINEAGE UNIQUE (REVIEW_LINEAGE_SHA256, ENRICHMENT_VERSION)
)
COMMENT = 'Private validated M4 AI result; base review facts remain independent of coverage';

GRANT USAGE ON SCHEMA REVIEWLENS.AI TO ROLE AI_ENRICH_ROLE;
GRANT SELECT, INSERT, UPDATE ON TABLE REVIEWLENS.AI.AI_REVIEW_ENRICHED TO ROLE AI_ENRICH_ROLE;

CREATE VIEW IF NOT EXISTS REVIEWLENS.AI.M4_ENRICHED_SCHEMA_COMPATIBILITY
COMMENT = 'Constant M4 committed-enrichment contract marker; contains no source data'
AS
SELECT
  'IMP-M4-011-COMMITTED-ENRICHMENT-V1'::VARCHAR(128) AS MIGRATION_ID,
  1::NUMBER(10, 0) AS SCHEMA_VERSION,
  'VALIDATED_ONLY'::VARCHAR(32) AS COMMIT_POLICY;
